/**
 * Identity API — sigchain + PUK envelope endpoints (Phase 6 / M2).
 *
 * These mirror the inline zod schemas in the worker routes (there are no
 * protocol-schema files for this surface yet):
 *   - apps/worker/routes/sigchain.ts  (GET/POST /api/users/:pubkey/sigchain)
 *   - apps/worker/routes/puk.ts       (POST /api/puk/envelopes, GET /api/puk/envelopes/:deviceId)
 *
 * All crypto happens in Rust via platform.ts; this module only moves the
 * resulting public material (signed link, HPKE envelope) to the server.
 */
import { request } from './client'
import type { HpkeEnvelope, SigchainLink } from '../platform'
import type { z } from 'zod'
import type { deviceDetailListResponseSchema } from '@protocol/schemas'

type DeviceDetailListResponse = z.infer<typeof deviceDetailListResponseSchema>
export type MyDevice = DeviceDetailListResponse['devices'][number]

/**
 * The caller's server-side device registry rows. The row id is generated by
 * POST /api/devices/register — it is NOT the CryptoState device id — and it is
 * what device-FK'd tables (puk_envelopes) key on, so the PUK envelope write
 * must use it rather than the local crypto device id.
 */
export async function getMyDevices(): Promise<MyDevice[]> {
  const res = await request<DeviceDetailListResponse>('/devices')
  return res.devices
}

// ---------------------------------------------------------------------------
// Types (mirror apps/worker/routes/sigchain.ts + puk.ts)
// ---------------------------------------------------------------------------

export type SigchainLinkType = 'genesis' | 'device_add' | 'device_remove' | 'key_rotate' | 'puk_epoch'

export interface SigchainLinkRecord {
  id: string
  userPubkey: string
  seqNo: number
  linkType: string
  payload: unknown
  signature: string
  /** null for the genesis link (seqNo 1). */
  prevHash: string | null
  hash: string
  signerDeviceId: string
  signerPubkey: string
  createdAt: string
}

export interface SigchainIntegrityBreak {
  seqNo: number
  reason: string
}

export interface SigchainResponse {
  links: SigchainLinkRecord[]
  /** Non-null when the chain's prevHash linkage is broken — do not trust `links`. */
  integrityBreak: SigchainIntegrityBreak | null
}

export interface PukEnvelopeRecord {
  id: string
  userPubkey: string
  deviceId: string
  generation: number
  /** base64url(kem_output || ciphertext) — see puk-envelopes schema. */
  envelope: string
  createdAt: string
}

// ---------------------------------------------------------------------------
// Sigchain
// ---------------------------------------------------------------------------

/** Fetch a user's full sigchain (self or admin). */
export async function getSigchain(pubkey: string): Promise<SigchainResponse> {
  return request<SigchainResponse>(`/users/${pubkey}/sigchain`)
}

/**
 * Append a signed sigchain link (self only).
 *
 * Maps the crate's `SigchainLink` (platform.ts) onto the worker's
 * `appendLinkBodySchema`. The server re-derives the canonical entry hash and
 * verifies the Ed25519 signature before persisting, so the fields here must
 * be exactly what `sigchainCreateLinkFromState` returned — no re-serialization
 * of the payload beyond parsing the JSON the crate already canonicalized.
 */
export async function appendSigchainLink(
  pubkey: string,
  link: SigchainLink,
  linkType: SigchainLinkType,
): Promise<SigchainLinkRecord> {
  return request<SigchainLinkRecord>(`/users/${pubkey}/sigchain`, {
    method: 'POST',
    body: JSON.stringify({
      seqNo: link.seq,
      linkType,
      payload: JSON.parse(link.payloadJson),
      signature: link.signature,
      prevHash: link.prevHash,
      hash: link.entryHash,
      signerDeviceId: link.signerDeviceId,
      signerPubkey: link.signerPubkey,
      timestamp: link.timestamp,
    }),
  })
}

// ---------------------------------------------------------------------------
// PUK envelopes
// ---------------------------------------------------------------------------

/**
 * Encode an HpkeEnvelope for the PUK-envelope wire format:
 * `base64url(kem_output || ciphertext)` (apps/worker/routes/puk.ts).
 *
 * `enc`/`ct` are already base64url in the envelope; decode, concatenate the
 * raw bytes, re-encode. The label id is not carried on the wire — the route
 * semantics fix it to LABEL_PUK_WRAP_TO_DEVICE, which the reader reconstructs
 * from the label registry when unwrapping.
 */
export function encodePukEnvelopeWire(envelope: HpkeEnvelope): string {
  const enc = base64urlDecodeLocal(envelope.enc)
  const ct = base64urlDecodeLocal(envelope.ct)
  const combined = new Uint8Array(enc.length + ct.length)
  combined.set(enc, 0)
  combined.set(ct, enc.length)
  return base64urlEncodeLocal(combined)
}

export interface PukEnvelopeInput {
  deviceId: string
  generation: number
  /** base64url(kem_output || ciphertext) — see encodePukEnvelopeWire. */
  envelope: string
}

export interface DistributePukEnvelopesResponse {
  distributed: number
  envelopes: PukEnvelopeRecord[]
}

/** Store PUK seed envelopes for devices (self). */
export async function distributePukEnvelopes(
  envelopes: PukEnvelopeInput[],
): Promise<DistributePukEnvelopesResponse> {
  return request('/puk/envelopes', {
    method: 'POST',
    body: JSON.stringify({ envelopes }),
  })
}

/** Fetch the latest PUK envelope for one of the caller's devices. */
export async function getPukEnvelope(deviceId: string): Promise<PukEnvelopeRecord> {
  return request<PukEnvelopeRecord>(`/puk/envelopes/${deviceId}`)
}

// ---------------------------------------------------------------------------
// base64url helpers (browser-local; platform.ts keeps its own private copies)
// ---------------------------------------------------------------------------

function base64urlDecodeLocal(b64url: string): Uint8Array {
  const padded = b64url.replace(/-/g, '+').replace(/_/g, '/') + '=='.slice(0, (4 - (b64url.length % 4)) % 4)
  const binary = atob(padded)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return bytes
}

function base64urlEncodeLocal(bytes: Uint8Array): string {
  let binary = ''
  for (const b of bytes) binary += String.fromCharCode(b)
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}
